### ISSUE TITLE
Performance issue of sequence parallelism on A100 after refactor

### ISSUE THREAD

**Issue by feifeibear** [xdit-project/xDiT#137]
Here is my script

```
export SCRIPT=pixartalpha_example.py
# export SCRIPT=sd3_example.py
export MODEL_ID="/mnt/models/SD/PixArt-XL-2-1024-MS"
# export MODEL_ID="/mnt/models/SD/HunyuanDiT-v1.2-Diffusers"
# export MODEL_ID="/mnt/models/SD/stable-diffusion-3-medium-diffusers"


for HEIGHT in 2048
do
for N_GPUS in 8;
do 


torchrun --nproc_per_node=$N_GPUS \
./examples/$SCRIPT \
--model $MODEL_ID \
--pipefusion_parallel_degree 1 \
--ulysses_degree 8 \
--ring_degree 1 \
--num_inference_steps 20 \
--warmup_steps 0 \
--height $HEIGHT \
--width $HEIGHT \
--num_pipeline_patch 8 \
--no_use_resolution_binning \
--prompt "A small dog" \


done
done
```

1. pipefusion_parallel_degree=8, ulysses_degree=1, ring_degree=1, not  use_split batch, num_pipeline_patch=8
epoch time: 3.98 sec, memory: 22.112337408 GB
legacy：3.37 sec

2. pipefusion_parallel_degree=1, ulysses_degree=8, ring_degree=1, not  use_split batch, num_pipeline_patch=8
epoch time: 11.00 sec, memory: 15.671771136 GB
legacy：2.46

3. pipefusion_parallel_degree=1, ulysses_degree=8, ring_degree=1, not  use_split batch, num_pipeline_patch=8
epoch time: 13.20 sec, memory: 15.671771136 GB

4. pipefusion_parallel_degree=1, ulysses_degree=4, ring_degree=1,  use_split batch, num_pipeline_patch=8
epoch time: 25.48 sec, memory: 23.379786752 GB

5. pipefusion_parallel_degree=4, ulysses_degree=1, ring_degree=1,  use_split batch, num_pipeline_patch=8
epoch time: 3.57 sec, memory: 22.901449728 GB

@Eigensystem told me that num_pipeline_patch should be 1. still very slow.
6. pipefusion_parallel_degree=4, ulysses_degree=1, ring_degree=1,  use_split batch, num_pipeline_patch=1
epoch time: 25.48 sec, memory: 23.379786752 GB

# problems
1. pipefusion is not as fast as the legacy version. I guess the reason maybe legacy do not count the vae module elapse? and the latest example script take vae into consideration.
2. The sequence parallel is too slow!

**Comment by Eigensystem** [comment]
The performance issues with Pipefusion were indeed caused by the legacy do not count the vae module elapse. Now, we have added a new option called "output_type" to bypass post-processing and VAE and edited the benchmark script. #140 
The performance issues related to sequential parallelism are still working in progress. #142
