### ISSUE TITLE
Thoughts to implement this on ODD number of GPUs?

### ISSUE THREAD

**Issue by alivisionrd** [xdit-project/xDiT#139]
Hey, I was wondering if I would like to run pipefusion on 3 GPUs, how would we go by it? Because right now in utils we have this assertion:  ` assert is_power_of_2(world_size) or parallelism == "pipefusion"
`

**Comment by Eigensystem** [comment]
You can try the examples in the root dir instead of the legacy dir now. We have removed is_power_of_2 limitation and support running pipeline on any number of devices.

**Comment by Steaunk** [comment]
> Okay thank you, does it mean we can run SD3 with pipefusion on any number of devices?
> and if I am interested to support it for ControlNet of SD3, how should I go about it?
> How will the strategy change for simple Unet based controlnets for SD and SDXL? 

Yes.

You can go through https://github.com/PipeFusion/PipeFusion/blob/main/legacy/pipefuser/pipelines/pip/distri_sd3.py and https://github.com/PipeFusion/PipeFusion/blob/main/pipefuser/pipelines/pipeline_pixart_alpha.py, which contain the change of pipeline. Based on it, you can create a SD3 pipeline with controlnet.

For SDXL, we had a branch for it before. But it's a bit hard to seperate the layers to different devices to achieve a balanced workload. If you have a better idea, you can submit a PR.

**Comment by alivisionrd** [comment]
Okay, but in the examples in the root dir there is only pix art present. How do I run SD3 for odd gpus? SD3 is using `DistriConfig` of distrifuser but pixart is using `EngineArgs`
Do I just rename `pipe = PipeFuserPixArtAlphaPipeline.from_pretrained `in **line 15** pixartalpha_example.py  to `pipe = DistriSD3Pipeline.from_pretrained` ?

**Comment by Steaunk** [comment]
> Okay, but in the examples in the root dir there is only pix art present. How do I run SD3 for odd gpus? SD3 is using `DistriConfig` of distrifuser but pixart is using `EngineArgs` Do I just rename `pipe = PipeFuserPixArtAlphaPipeline.from_pretrained `in **line 15** pixartalpha_example.py to `pipe = DistriSD3Pipeline.from_pretrained` ?

Currently, we are refactoring the project, so there are two versions of PipeFusion: legacy supports PixArtAlpha, SD3, hunyuan, while the new one support PixArtAlpha & Sigma and we are migrating other models now. I think if you wanna add controlnet for SD3, you can try with legacy first or wait for migrating SD3.

**Comment by alivisionrd** [comment]
Hey guys, I tried to integrate **Control Net SD3** in legacy.
1) I changed the "call" function of `legacy/pipefuser/pipelines/pip/distri_sd3.py `accordingly to the requirement of `StableDiffusion3ControlNetPipeline` call function
2) I made separate `DistriDiTSD3PipeFusionCN` to make `controlnet = DistriDiTSD3PipeFusionCN(controlnet,distri_config)` in `from_pretrained `function of sd3.py
3) I also made `seperate pip_forward_cn` in call function distri_sd3.py

**I am getting different image for 1GPU and 2GPU**. I think I should do **communication** of either **control_image** or **control_block_samples** just like you are doing communication before invoking the pip_forward i.e.` latents = self.comm_manager.get_data() , latents[batch_idx] = self.comm_manager.get_data(idx=batch_idx), self.comm_manager.send_to_next(next_encoder_hidden_states, is_extra=True)`

Can you please guide me on which thing should I perform communication, control_image or control_block_samples  and how to ? because controlnet expects this: 

```
                    **next_control_block_samples** = self.pip_forward_cn(
                    latents[batch_idx],
                    encoder_hidden_states,
                    t,
                    pooled_prompt_embeds,
                    timestep_expand_shape,
                    cond_scale=cond_scale,
                    **control_image = control_image[batch_idx],**
                    controlnet_pooled_projections = controlnet_pooled_projections

                )
```
Here is image generated from my implementation of  2GPUs pipefusion legacy 
![_pipefusion_hw_1024_sync_corrected_async_gn_sp_False_u1_w2_mb4](https://github.com/user-attachments/assets/e040124d-96c0-4d97-809d-877c0fee0091)
Whereas, the image should look like this:
![sd3_cn_1024](https://github.com/user-attachments/assets/cb3864de-57ca-4113-9ec0-ffd7eef74ca6)

**Comment by Steaunk** [comment]
I think we don't need to communicate `control_image` since it doesn't change throughout the steps. Could you submit a PR so that I can have a look in details?

**Comment by alivisionrd** [comment]
Okay I will submit the PR in a while by the username "mali-afridi"

**Comment by alivisionrd** [comment]
Hey, I have created a PR using my other id "mali-afridi"
Please have a look: [here](https://github.com/xdit-project/xDiT/pull/149)

**Comment by feifeibear** [comment]
The PR has been merged. Thanks for your contribution.
