### ISSUE TITLE
Image Difference for SD3 in the refactored code, when pipefusion_parallel_degree changes

### ISSUE THREAD

**Issue by khadijairfan2345** [xdit-project/xDiT#163]
[
![stable_diffusion_3_result_dp1_cfg1_ulysses1_ringNone_pp1_patchNone_0](https://github.com/user-attachments/assets/1f031578-d2c4-4314-a936-f2c53c70182f)
](url)
![stable_diffusion_3_result_dp1_cfg1_ulysses1_ringNone_pp2_patchNone_0](https://github.com/user-attachments/assets/9ed39f1c-2313-411b-823f-8c607bfe2012)
![stable_diffusion_3_result_dp1_cfg1_ulysses1_ringNone_pp3_patchNone_0](https://github.com/user-attachments/assets/81b3bd0a-b8a6-4d02-8952-47bf2cf12694)
![stable_diffusion_3_result_dp1_cfg1_ulysses1_ringNone_pp4_patchNone_0](https://github.com/user-attachments/assets/560f488a-ad30-4b4a-a3b2-6dc201518bba)

The refactored code of SD3 runs successfully on 1, 2, 3, and 4 GPUS, however, _**the issue of image difference persists**_. Keeping all other parameters constant, but pipefusion_parallel_degree yields different as depicted by the images attached. What is the solution for this, and why is there a difference occurring?

### Commands

1. `torchrun --nproc_per_node=1  --master_port=29503  examples/sd3_example.py --pipefusion_parallel_degree 1 --ulysses_degree 1  --num_inference_steps 28 --warmup_steps 0 --prompt "A small dog"
`
2. `torchrun --nproc_per_node=2  --master_port=29503  examples/sd3_example.py --pipefusion_parallel_degree 2 --ulysses_degree 1  --num_inference_steps 28 --warmup_steps 0 --prompt "A small dog"
`
3. `torchrun --nproc_per_node=3  --master_port=29503  examples/sd3_example.py --pipefusion_parallel_degree 3 --ulysses_degree 1  --num_inference_steps 28 --warmup_steps 0 --prompt "A small dog"
`
4. `torchrun --nproc_per_node=4  --master_port=29503  examples/sd3_example.py --pipefusion_parallel_degree 4 --ulysses_degree 1  --num_inference_steps 28 --warmup_steps 0 --prompt "A small dog"`

**Comment by Steaunk** [comment]
#114 A known issue.
