### ISSUE TITLE
Whether HunyuanDiT-v1.2-Diffusers  supports the method Sequence Parallelism 

### ISSUE THREAD

**Issue by linuxmi** [xdit-project/xDiT#167]
Whether HunyuanDiT-v1.2-Diffusers  supports the method Sequence Parallelism

**Comment by feifeibear** [comment]
HunyuanDiT uses the legacy version, which supports CFG parallel + PipeFusion, not support SP. We are planning to support it with the latest API. Would you like to help us with this?

**Comment by feifeibear** [comment]
@linuxmi 
HunyuanDiT has already support SP+PipeFusion+CFG+Data Hybrid Parallelism.

Note that SP degree <= 2. We found if sp_degree = 4, the output is wrong. But sp=2 is definitely correct.

https://github.com/xdit-project/xDiT/blob/main/examples/run.sh
