### ISSUE TITLE
[SERVER] Can give a http interface example?

### ISSUE THREAD

**Issue by senlyu163** [xdit-project/xDiT#185]
Nice work.

This project aims to improve the efficiency of server inference. Can you give an example of http interface calling?

**Comment by feifeibear** [comment]
OK, we are going to give an example.

**Comment by feifeibear** [comment]
We are going to provide a ComfyUI inference. I believe that is what you what.

**Comment by senlyu163** [comment]
> We are going to provide a ComfyUI inference. I believe that is what you what.

amazzzzing! Can't wait it!
