### ISSUE TITLE
运行CogVideoX-2b模型显示缺少bin文件

### ISSUE THREAD

**Issue by WeYeYeYeYe** [xdit-project/xDiT#253]
在运行example/run.sh的 CogVideoX-2b模型时，出现报错
OSError: Error no file named diffusion_pytorch_model.bin found in directory /home/dataset/CogVideoX-2b/transformer.
且在CogVideoX-2b仓库下的transformer中没找到这个文件，只有diffusion_pytorch_model.safetensors

**Comment by xibosun** [comment]
请问 xfuser 是如何安装的，另外麻烦运行 pip list 提供一下各种包的版本信息，谢谢。

**Comment by WeYeYeYeYe** [comment]
[pip.txt](https://github.com/user-attachments/files/16901729/pip.txt)
是用pip装的，版本信息在文件里，谢谢！

**Comment by WeYeYeYeYe** [comment]
> [pip.txt](https://github.com/user-attachments/files/16901729/pip.txt) 是用pip装的，版本信息在文件里，谢谢！



> 请问 xfuser 是如何安装的，另外麻烦运行 pip list 提供一下各种包的版本信息，谢谢。

是用pip装的，版本信息在文件里，谢谢！
[pip.txt](https://github.com/user-attachments/files/16901736/pip.txt)

**Comment by feifeibear** [comment]
应该是你没有正确下载CogVideoX-2b，这个文件下面文件有25GB

25G     /cfs/dit/CogVideoX-2b
❯ tree /cfs/dit/CogVideoX-2b
/cfs/dit/CogVideoX-2b
├── LICENSE
├── model_index.json
├── README.md
├── README_zh.md
├── scheduler
│   └── scheduler_config.json
├── text_encoder
│   ├── config.json
│   ├── model-00001-of-00002.safetensors
│   ├── model-00002-of-00002.safetensors
│   └── model.safetensors.index.json
├── tokenizer
│   ├── added_tokens.json
│   ├── special_tokens_map.json
│   ├── spiece.model
│   └── tokenizer_config.json
├── transformer
│   ├── config.json
│   └── diffusion_pytorch_model.safetensors
└── vae
    ├── config.json
    └── diffusion_pytorch_model.safetensors

**Comment by WeYeYeYeYe** [comment]
> 应该是你没有正确下载CogVideoX-2b，这个文件下面文件有25GB
> 
> 25G /cfs/dit/CogVideoX-2b ❯ tree /cfs/dit/CogVideoX-2b /cfs/dit/CogVideoX-2b ├── LICENSE ├── model_index.json ├── README.md ├── README_zh.md ├── scheduler │ └── scheduler_config.json ├── text_encoder │ ├── config.json │ ├── model-00001-of-00002.safetensors │ ├── model-00002-of-00002.safetensors │ └── model.safetensors.index.json ├── tokenizer │ ├── added_tokens.json │ ├── special_tokens_map.json │ ├── spiece.model │ └── tokenizer_config.json ├── transformer │ ├── config.json │ └── diffusion_pytorch_model.safetensors └── vae ├── config.json └── diffusion_pytorch_model.safetensors

重新下载之后解决了，谢谢！
