### ISSUE TITLE
ValueError: Attention Processor class CogVideoXAttnProcessor2_0 is not supported by xFuser

### ISSUE THREAD

**Issue by WeYeYeYeYe** [xdit-project/xDiT#254]
在运行CogVideoX-2b模型时，出现报错：
ValueError: Attention Processor class CogVideoXAttnProcessor2_0 is not supported by xFuser
请问xDiT对于CogVideoX-2b的版本有要求吗？我使用的是目前（9.6）huggingface中的最新版
我的pip list如下
[pip.txt](https://github.com/user-attachments/files/16902022/pip.txt)

**Comment by Eigensystem** [comment]
对的，由于之前版本diffusers用的attn_processor不是`CogVideoXAttnProcessor2_0`，我们暂未支持。应该会在最近fix

**Comment by WeYeYeYeYe** [comment]
> 对的，由于之前版本diffusers用的attn_processor不是`CogVideoXAttnProcessor2_0`，我们暂未支持。应该会在最近fix

之前用的CogVideoX-2b是什么版本呢？

**Comment by dannyxiaocn** [comment]
diffusers commit id 16a3dad474dad00f8e4071d699e1562471a2dacd 这个版本

**Comment by WeYeYeYeYe** [comment]
> diffusers commit id 16a3dad474dad00f8e4071d699e1562471a2dacd 这个版本

好的谢谢！
