### ISSUE TITLE
变量is_dp_last_group未定义

### ISSUE THREAD

**Issue by WeYeYeYeYe** [xdit-project/xDiT#256]
报错信息如下：
[rank0]:   File "/xDiT/xfuser/model_executor/pipelines/pipeline_cogvideox.py", line 360, in __call__
[rank0]:     if is_dp_last_group():
[rank0]: NameError: name 'is_dp_last_group' is not defined

**Comment by feifeibear** [comment]
Thanks for pointing out the problem. please pull the latest commit.

**Comment by weyeeji** [comment]
> Thanks for pointing out the problem. please pull the latest commit.

在stable diffusion中出现了相同的问题，我是使用pip install xfuser安装的，是否这个问题跟之前cogvideo的一样？

**Comment by feifeibear** [comment]
> > Thanks for pointing out the problem. please pull the latest commit.
> 
> 在stable diffusion中出现了相同的问题，我是使用pip install xfuser安装的，是否这个问题跟之前cogvideo的一样？

贴一下你的报错，sd3么？

**Comment by weyeeji** [comment]
> > > Thanks for pointing out the problem. please pull the latest commit.
> > 
> > 
> > 在stable diffusion中出现了相同的问题，我是使用pip install xfuser安装的，是否这个问题跟之前cogvideo的一样？
> 
> 贴一下你的报错，sd3么？

是sd3，报错信息如下：
AttributeError: 'StableDiffusion3Pipeline' object has no attribute 'is_dp_last_group'
