### ISSUE TITLE
Why xDiT-0.3.2 attention_processor no longer supported  support FluxSingleAttnProcessor2_0 ?

### ISSUE THREAD

**Issue by Lohnwave** [xdit-project/xDiT#303]
I found FluxSingleAttnProcessor2_0 support in xDiT-0.3.1 and 0.3.
But xDiT-0.3.2 attention_processor no longer supported  support FluxSingleAttnProcessor2_0

**Comment by Eigensystem** [comment]
Because xdit currently relies on the main branch of diffusers, where `FluxSingleTransformerBlock` uses `FluxAttnProcessor2_0` instead of the previous version of `FluxSingleAttnProcessor2_0`.

**Comment by feifeibear** [comment]
diffusers quickly change the flux interface. We decided to follow the latest version.
