### ISSUE TITLE
can't run with docker

### ISSUE THREAD

**Issue by James-Dao** [xdit-project/xDiT#315]
he cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
WARNING 10-23 11:10:27 [args.py:246] Distributed environment is not initialized. Initializing...
DEBUG 10-23 11:10:27 [parallel_state.py:179] world_size=-1 rank=-1 local_rank=-1 distributed_init_method=env:// backend=nccl
[W1023 11:10:27.722704281 Utils.hpp:164] Warning: Environment variable NCCL_BLOCKING_WAIT is deprecated; use TORCH_NCCL_BLOCKING_WAIT instead (function operator())
[W1023 11:10:27.722747060 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
INFO 10-23 11:10:27 [config.py:137] Pipeline patch number not set, using default value 1
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.03s/it]it/s]
Loading pipeline components...:  86%|████████▌ | 6/7 [00:12<00:03,  3.09s/it]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|██████████| 7/7 [00:12<00:00,  1.81s/it]
WARNING 10-23 11:10:40 [runtime_state.py:64] Model parallel is not initialized, initializing...
INFO 10-23 11:10:40 [base_pipeline.py:236] Transformer backbone found, but model parallelism is not enabled, use naive model
INFO 10-23 11:10:40 [base_pipeline.py:286] Scheduler found, paralleling scheduler...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/app/./comfyui-xdit/host.py", line 247, in <module>
[rank0]:     initialize()
[rank0]:   File "/app/./comfyui-xdit/host.py", line 98, in initialize
[rank0]:     pipe.prepare_run(input_config)
[rank0]: TypeError: xFuserFluxPipeline.prepare_run() missing 1 required positional argument: 'max_sequence_length'
[rank0]:[W1023 11:10:46.587157521 ProcessGroupNCCL.cpp:1187] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E1023 11:10:46.961000 140381205272384 torch/distributed/elastic/multiprocessing/api.py:832] failed (exitcode: 1) local_rank: 0 (pid: 73) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.0a0+3bcc3cddb5.nv24.7', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 900, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 891, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./comfyui-xdit/host.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-23_11:10:46
  host      : flux1-schnell-xdit-769ff86d79-8wj76
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 73)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/app/comfyui-xdit/launch_host.py", line 45, in <module>
    main()
  File "/app/comfyui-xdit/launch_host.py", line 41, in main
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['torchrun', '--nproc_per_node=1', './comfyui-xdit/host.py', '--model=/tmp/FLUX.1-schnell', '--pipefusion_parallel_degree=1', '--ulysses_degree=1', '--ring_degree=1', '--height=512', '--width=512']' returned non-zero exit status 1.

**Comment by feifeibear** [comment]
docker run --gpus all -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -p 6000:6000 -v /cfs:/cfs xdit-server:0.3.1 --config ./config.json

did you launch the service docker image with correct config file?

**Comment by James-Dao** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: xdit-config
  namespace: qwen-72b
data:
  config.json: |
    {
        "nproc_per_node": 1,
        "model": "/tmp/FLUX.1-schnell",
        "pipefusion_parallel_degree": 1,
        "ulysses_degree": 1,
        "ring_degree": 1,
        "height": 512,
        "width": 512,
        "save_disk_path": "/cfs/dit/output",
        "use_cfg_parallel": false,
        "max_sequence_length": 256
    }

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: flux1-schnell-xdit
  namespace: qwen-72b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux1-schnell-xdit
  template:
    metadata:
      labels:
        app: flux1-schnell-xdit
    spec:
      containers:
        - name: flux1-schnell-xdit
          env:
          - name: VLLM_WORKER_MULTIPROC_METHOD
            value: spawn
          image: flux1-schnell:xdit-amd64-v0.3.1
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: '36'
              memory: 64Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '12'
              memory: 32Gi
              nvidia.com/gpu: '1'
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          volumeMounts:
            - mountPath: /tmp/FLUX.1-schnell
              name: llms
            - name: config-volume
              mountPath: /app/comfyui-xdit/config.json
              subPath: config.json
          imagePullPolicy: IfNotPresent
      volumes:
      - hostPath:
          path: /root/llms/FLUX.1-schnell
          type: ""
        name: llms
      - name: config-volume
        configMap:
          name: xdit-config

**Comment by James-Dao** [comment]
i use k8s to run it.

**Comment by feifeibear** [comment]
thufeifeibear/xdit-dev:0.3.2

here is a development env. it has installed all dependencies (the most terrible one is flash_attn).

you can set your own launch script

**Comment by James-Dao** [comment]
ok, i will try to update version from 0.3.1 to 0.3.2。

**Comment by James-Dao** [comment]
run success. if i want to use it on production, what should i do ?

**Comment by James-Dao** [comment]
if i test it with 2 concurecy , it will run into error. error detail is :

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/./comfyui-xdit/host.py", line 195, in generate_image
    output, elapsed_time = generate_image_parallel(*params)
  File "/app/./comfyui-xdit/host.py", line 110, in generate_image_parallel
    output = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 133, in data_parallel_fn
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 147, in check_naive_forward_fn
    return self.module(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/flux/pipeline_flux.py", line 635, in __call__
    ) = self.encode_prompt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/flux/pipeline_flux.py", line 349, in encode_prompt
    prompt_embeds = self._get_t5_prompt_embeds(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/flux/pipeline_flux.py", line 225, in _get_t5_prompt_embeds
    untruncated_ids = self.tokenizer_2(prompt, padding="longest", return_tensors="pt").input_ids
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3055, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3142, in _call_one
    return self.batch_encode_plus(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3338, in batch_encode_plus
    return self._batch_encode_plus(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 517, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 452, in set_truncation_and_padding
    self._tokenizer.no_truncation()
RuntimeError: Already borrowed
[Rank 0] 2024-10-24 04:30:03 - INFO - 127.0.0.1 - - [24/Oct/2024 04:30:03] "POST /generate HTTP/1.1" 500 -
100%|██████████| 28/28 [00:02<00:00, 11.24it/s]
[Rank 0] 2024-10-24 04:30:05 - INFO - Image generation completed in 2.66 seconds
[Rank 0] 2024-10-24 04:30:05 - INFO - Image saved to: /tmp/generated_image_20241024-043005.png
[Rank 0] 2024-10-24 04:30:05 - INFO - 127.0.0.1 - - [24/Oct/2024 04:30:05] "POST /generate HTTP/1.1" 200 -

**Comment by James-Dao** [comment]
root@flux1-schnell-xdit-6445785fd-cx6gz:/app# ./test.sh 
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

real    0m0.092s
user    0m0.009s
sys     0m0.015s

{"elapsed_time":"2.66 sec","message":"Image generated successfully","output":"/tmp/generated_image_20241024-043005.png","save_to_disk":true}

real    0m2.885s
user    0m0.008s
sys     0m0.018s
所有并发请求已完成。

**Comment by James-Dao** [comment]
#!/bin/bash

# 目标 URL
URL="http://localhost:6000/generate"

# 并发数量
CONCURRENCY_LEVEL=1

# JSON 数据
JSON_DATA='{
    "prompt": "A lovely rabbit",
    "num_inference_steps": 28,
    "save_disk_path": "/tmp"
}'

# 发起并发请求
for ((i=1; i<=CONCURRENCY_LEVEL; i++)); do
    time curl -X POST "$URL" \
        -H "Content-Type: application/json" \
        -d "$JSON_DATA" &
done

# 等待所有后台任务完成
wait

echo "所有并发请求已完成。"

**Comment by James-Dao** [comment]
#!/bin/bash

# 目标 URL
URL="http://localhost:6000/generate"

# 并发数量
CONCURRENCY_LEVEL=2

# JSON 数据
JSON_DATA='{
    "prompt": "A lovely rabbit",
    "num_inference_steps": 28,
    "save_disk_path": "/tmp"
}'

# 发起并发请求
for ((i=1; i<=CONCURRENCY_LEVEL; i++)); do
    time curl -X POST "$URL" \
        -H "Content-Type: application/json" \
        -d "$JSON_DATA" &
done

# 等待所有后台任务完成
wait

echo "所有并发请求已完成。"

**Comment by James-Dao** [comment]
config is : 

apiVersion: v1
kind: ConfigMap
metadata:
  name: xdit-config
  namespace: qwen-72b
data:
  config.json: |
    {
        "nproc_per_node": 1,
        "model": "/tmp/FLUX.1-schnell",
        "pipefusion_parallel_degree": 1,
        "ulysses_degree": 1,
        "ring_degree": 1,
        "height": 512,
        "width": 512,
        "save_disk_path": "/cfs/dit/output",
        "use_cfg_parallel": false
    }

**Comment by feifeibear** [comment]
https://github.com/xdit-project/xDiT/blob/main/docs/developer/Http_Service.md
follow这个文档，就可以启动一个http服务了
