### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by Reginald-L** [xdit-project/xDiT#318]
I use 4 L20 (each GPU with 46G) to run flux-dev, but I got OOM
here is my code and log:
![image](https://github.com/user-attachments/assets/0a74522f-ca5e-47dc-8a06-35849bd32f55)
![image](https://github.com/user-attachments/assets/9c4108b5-a58d-4b18-b73a-3a49997f1e39)
![image](https://github.com/user-attachments/assets/71455b75-b23b-41c3-850f-ec286f3b060f)

is there any mistake in my code? May I get any help?

**Comment by feifeibear** [comment]
Can you successfully run our example code?
https://github.com/xdit-project/xDiT/blob/main/examples/run.sh

It seems you did not initialize the distributed enviroment.

**Comment by Reginald-L** [comment]
> Can you successfully run our example code? https://github.com/xdit-project/xDiT/blob/main/examples/run.sh
> 
> It seems you did not initialize the distributed enviroment.

yep, I can run the examples/run.sh file successfully

**Comment by Reginald-L** [comment]
> Can you successfully run our example code? https://github.com/xdit-project/xDiT/blob/main/examples/run.sh
> 
> It seems you did not initialize the distributed enviroment.

yep, I can run the examples/run.sh file successfully
