### ISSUE TITLE
Is there a plan to support opensora and opensora plan models

### ISSUE THREAD

**Issue by Bensong0506** [xdit-project/xDiT#321]

**Comment by feifeibear** [comment]
We found that there are two open-soras in China. Both of them are not interpreted in huggingface diffusers. We are not sure if they really be applied by users worldwide. We will support them if they are in the diffusers.

**Comment by Bensong0506** [comment]
I see, thanks. Is there any technical difficulty supporting Opensora related models, as they are both 3d VAEs similar to Cogvideo models, I think it should be very similar? Thanks a lot for your reply!

**Comment by feifeibear** [comment]
I believe there is no technical difficulty. xDiT has supports Latte. As far as I know, OpenSoras build their model architecture based on Latte? I am not sure. If you would like to apply xDiT on OpenSoras, we can help you on this topic.

**Comment by Bensong0506** [comment]
Thanks a lot, I will first try the CogVideoX and see if everything works.
