### ISSUE TITLE
AttributeError: 'CogVideoXDecoder3D' object has no attribute 'conv_norm_out'

### ISSUE THREAD

**Issue by Bensong0506** [xdit-project/xDiT#322]
I got this error when running Cogvideo example using parallel_vae. Attached is my .sh file. Does this mean xDiT does not support distVAE for Cogvideo yet?

![Screenshot 2024-10-29 111808](https://github.com/user-attachments/assets/8707fc5f-5633-471e-99ba-5e619eb311b2)

**Comment by machengcheng2016** [comment]
same here

**Comment by xibosun** [comment]
Please kindly comment out Line 24 in the figure (PARALLEL_VAE="--use_parallel_vae"), as CogVideo in xDiT does not support parallel VAE.
