### ISSUE TITLE
About DSP

### ISSUE THREAD

**Issue by xesdiny** [xdit-project/xDiT#323]
I think [DSP(Dynamic Sequence Parallelism)](https://arxiv.org/abs/2403.10266) is able to outperform DeepSpeed-Ulysses(all2all reduce) by 32% to 75%.
On PCIe & Ethernet env,DSP is better than DeepSpeed-Ulysses?

**Comment by feifeibear** [comment]
As far as I know, DSP is applied to a special attention block in Latte (spatial+temperal attention, which is not applied in latest DiTs, like CogVideoX, Flux.1 and SD3. Correct me if I am wrong.

**Comment by xesdiny** [comment]
Emm,spatial+temperal attention diff  just a difference in how the activation converts 3d to 2d. The former integrates `t` into `b`, while the latter integrates `hxw` into `b`. I think you can look at the details of USP and DSP.

> As far as I know, DSP is applied to a special attention block in Latte (spatial+temperal attention, which is not applied in latest DiTs, like CogVideoX, Flux.1 and SD3. Correct me if I am wrong.

**Comment by xesdiny** [comment]
You must understand that USP is designed to combine Ulysses and Ring Attention. Its goal is to improve efficiency within limited bandwidth and remove redundant communication overhead.

**Comment by xesdiny** [comment]
**I did make a mistake in understanding.**
DSP is indeed designed around the Attention of each dimension in multiple dimensions. Since the sequence is very short in time, it does not even need sequence parallelism to reduce the all2all communication overhead. Moreover, the dimension of sequence parallelism is still at the attn_block external level. Ulysses & USP both complete sequence parallelism at the qkv level. Although neither implements context Parallel, the current USP based on all2all implementation between adjacent drivers can indeed reduce a lot of communication (can we consider ringReduce to reduce bandwidth here?)

**Comment by xesdiny** [comment]
By the way,Will the PipeFusion strategy be adapted to Cogvideox in the near future?

**Comment by feifeibear** [comment]
> @feifeibear **I did make a mistake in understanding.** DSP is indeed designed around the Attention of each dimension in multiple dimensions. Since the sequence is very short in time, it does not even need sequence parallelism to reduce the all2all communication overhead. Moreover, the dimension of sequence parallelism is still at the attn_block external level. Ulysses & USP both complete sequence parallelism at the qkv level. Although neither implements context Parallel, the current USP based on all2all implementation between adjacent drivers can indeed reduce a lot of communication (can we consider ringReduce to reduce bandwidth here?)

So what is the conclusion? Can we use DSP for CogVideoX? I noticed that VideoSys dose not apply DSP for CogVideoX.

**Comment by feifeibear** [comment]
> By the way,Will the PipeFusion strategy be adapted to Cogvideox in the near future? If I choose to cancel the Ring Attention and split the kv in parallel, can I achieve this kind of Gpipe reuse of the state kv of the previous timestamp?

We are planing to design a more efficient parallel approach for CogVideoX, which may more aggressively leverage redundancy.

**Comment by xesdiny** [comment]
> Can we use DSP for CogVideoX? I noticed that VideoSys dose not apply DSP for CogVideoX.

I think the implementation of DSP strategy refers to completing DP segmentation in spatial and temperal . 
CogvideoX's mmDit for 3d-full attention cannot be applied to its strategy. 
I feel that it can provide certain assistance in the 2.5D Dit structure, and it does not care about **the difficulties about the  long-term attention** at all.

**Comment by feifeibear** [comment]
> > Can we use DSP for CogVideoX? I noticed that VideoSys dose not apply DSP for CogVideoX.
> 
> I think the implementation of DSP strategy refers to completing DP segmentation in spatial and temperal . CogvideoX's mmDit for 3d-full attention cannot be applied to its strategy. I feel that it can provide certain assistance in the 2.5D Dit structure, and it does not care about **the difficulties about the long-term attention** at all.

OK, we now arrive at the conclusion that DSP is not applicable in Flux.1 and SD3 and CogVideoX.
