### ISSUE TITLE
SD3-medium OOM on xDiT with 2x4090 but fine on diffusers with 1x4090

### ISSUE THREAD

**Issue by wxsms** [xdit-project/xDiT#343]
model: official sd3 medium

inputs: 1024x1024, bs=4

diffusers with 1x4090 (works fine):

```python
from diffusers import StableDiffusion3Pipeline
import torch

pipe = StableDiffusion3Pipeline.from_pretrained(
    "/mnt/models/source", 
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)
pipe = pipe.to('cuda:0')
prompt = "ghibli style, a fantasy landscape with castles"
image = pipe(
    [prompt] * 4,
    num_inference_steps=12,
    generator=torch.Generator("cuda").manual_seed(42),
    width=1024,
    height=1024,
).images[0]
```

xDiT with 2x4090 and official `sd3_example.py` code (OOM):

```bash
set -ex

gpu=2
prompt="ghibli style, a fantasy landscape with castles"

args=(
  --model /mnt/models/source/
  # none of these works to avaoid OOM
  # --pipefusion_parallel_degree ${gpu}
  # --tensor_parallel_degree 2
  # --data_parallel_degree 2
  --use_cfg_parallel
  --height 1024
  --width 1024
  --prompt "$prompt" "$prompt" "$prompt" "$prompt"
  --num_inference_steps 12
  --seed 42
  --no_use_resolution_binning
  # none of these works to avaoid OOM
  # --enable_sequential_cpu_offload
  # --enable_model_cpu_offload
  # --enable_tiling
  # --enable_slicing
)

torchrun --nproc_per_node=${gpu} sd3_example.py "${args[@]}"
```

detail logs

<details>
<pre><code>
+ torchrun --nproc_per_node=2 sd3_example.py --model /mnt/models/source/ --use_cfg_parallel --height 1024 --width 1024 --prompt 'ghibli style, a fantasy landscape with castles' 'ghibli style, a fantasy landscape with castles' 'ghibli style, a fantasy landscape with castles' 'ghibli style, a fantasy landscape with castles' --num_inference_steps 12 --seed 42 --no_use_resolution_binning
W1111 16:02:35.275000 376341 torch/distributed/run.py:793] 
W1111 16:02:35.275000 376341 torch/distributed/run.py:793] *****************************************
W1111 16:02:35.275000 376341 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1111 16:02:35.275000 376341 torch/distributed/run.py:793] *****************************************
WARNING 11-11 16:02:38 [args.py:320] Distributed environment is not initialized. Initializing...
DEBUG 11-11 16:02:38 [parallel_state.py:179] world_size=-1 rank=-1 local_rank=-1 distributed_init_method=env:// backend=nccl
WARNING 11-11 16:02:38 [args.py:320] Distributed environment is not initialized. Initializing...
DEBUG 11-11 16:02:38 [parallel_state.py:179] world_size=-1 rank=-1 local_rank=-1 distributed_init_method=env:// backend=nccl
INFO 11-11 16:02:38 [config.py:114] Ulysses degree not set, using default value 1
INFO 11-11 16:02:38 [config.py:119] Ring degree not set, using default value 1
INFO 11-11 16:02:38 [config.py:114] Ulysses degree not set, using default value 1
INFO 11-11 16:02:38 [config.py:163] Pipeline patch number not set, using default value 1
INFO 11-11 16:02:38 [config.py:119] Ring degree not set, using default value 1
INFO 11-11 16:02:38 [config.py:163] Pipeline patch number not set, using default value 1
Loading pipeline components...:  56%|██████████████████████████████████████████████                                     | 5/9 [00:01<00:00,  7.13it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...:  44%|████████████████████████████████████▉                                              | 4/9 [00:01<00:01,  3.49it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.27it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.28it/s]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.87it/s]
WARNING 11-11 16:02:41 [runtime_state.py:63] Model parallel is not initialized, initializing...
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.85it/s]
WARNING 11-11 16:02:41 [runtime_state.py:63] Model parallel is not initialized, initializing...
INFO 11-11 16:02:41 [base_pipeline.py:290] Transformer backbone found, paralleling transformer...
INFO 11-11 16:02:41 [base_pipeline.py:290] Transformer backbone found, paralleling transformer...
INFO 11-11 16:02:41 [base_pipeline.py:335] Scheduler found, paralleling scheduler...
INFO 11-11 16:02:41 [base_pipeline.py:335] Scheduler found, paralleling scheduler...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.82it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.25it/s]
  0%|                                                                                                                          | 0/12 [00:00<?, ?it/s][rank1]: Traceback (most recent call last):
[rank1]:   File "/data/script/sd3_xdit/sd3_example.py", line 78, in <module>
[rank1]:     main()
[rank1]:   File "/data/script/sd3_xdit/sd3_example.py", line 30, in main
[rank1]:     pipe.prepare_run(input_config)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/pipeline_stable_diffusion_3.py", line 75, in prepare_run
[rank1]:     self.__call__(
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 166, in data_parallel_fn
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 186, in check_naive_forward_fn
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/pipeline_stable_diffusion_3.py", line 397, in __call__
[rank1]:     image = vae_decode(latents)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/pipeline_stable_diffusion_3.py", line 388, in vae_decode
[rank1]:     image = self.vae.decode(latents, return_dict=False)[0]
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
[rank1]:     return method(self, *args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 326, in decode
[rank1]:     decoded = self._decode(z).sample
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 297, in _decode
[rank1]:     dec = self.decoder(z)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/vae.py", line 337, in forward
[rank1]:     sample = up_block(sample, latent_embeds)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unets/unet_2d_blocks.py", line 2750, in forward
[rank1]:     hidden_states = upsampler(hidden_states)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/upsampling.py", line 180, in forward
[rank1]:     hidden_states = self.conv(hidden_states)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 554, in forward
[rank1]:     return self._conv_forward(input, self.weight, self.bias)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
[rank1]:     return F.conv2d(
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB. GPU 1 has a total capacity of 23.65 GiB of which 1.97 GiB is free. Process 176019 has 21.67 GiB memory in use. Of the allocated memory 19.90 GiB is allocated by PyTorch, and 1.19 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
W1111 16:02:49.722000 376341 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 376445 closing signal SIGTERM
E1111 16:02:49.937000 376341 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 376446) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
sd3_example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-11_16:02:49
  host      : atmodels-optim-v2-bmv2x-4289114995
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 376446)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
</pre></code>
</details>

**Comment by feifeibear** [comment]
You meet OOM in VAE module.
you can add this flag.
--use_parallel_vae

**Comment by wxsms** [comment]
Thank you for response! A new error encounted after added `--use_parallel_vae`:

```
Patch vae: [elapsed_time: 0.88 sec, peak_memory: 23.042696704 GB]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/script/sd3_xdit/sd3_example.py", line 79, in <module>
[rank0]:     main()
[rank0]:   File "/data/script/sd3_xdit/sd3_example.py", line 31, in main
[rank0]:     pipe.prepare_run(input_config)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/pipeline_stable_diffusion_3.py", line 75, in prepare_run
[rank0]:     self.__call__(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 166, in data_parallel_fn
[rank0]:     return func(self, *args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/base_pipeline.py", line 186, in check_naive_forward_fn
[rank0]:     return func(self, *args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xfuser/model_executor/pipelines/pipeline_stable_diffusion_3.py", line 403, in __call__
[rank0]:     image = self.image_processor.postprocess(image, output_type=output_type)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/image_processor.py", line 765, in postprocess
[rank0]:     image = self.pt_to_numpy(image)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/image_processor.py", line 208, in pt_to_numpy
[rank0]:     images = images.cpu().permute(0, 2, 3, 1).float().numpy()
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by feifeibear** [comment]
can you use a single prompt for test? If you passed multiple prompt to the pipeline, it will apply DP.

**Comment by wxsms** [comment]
Thanks. I also works after I remove T5XXL.
