### ISSUE TITLE
flux-dev run error

### ISSUE THREAD

**Issue by algorithmconquer** [xdit-project/xDiT#354]
../xfuser/model_executor/layers/attention_processor.py", line 102, in apply_rotary_emb
[rank1]:     out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
[rank1]: RuntimeError: The size of tensor a (4352) must match the size of tensor b (4608) at non-singleton dimension 2

**Comment by feifeibear** [comment]
what is your run script?

**Comment by algorithmconquer** [comment]
@feifeibear torchrun --nproc_per_node=2 flux_example.py --model ./flux.1-dev/ --pipefusion_parallel_degree 2 --height 1024 --width 1024 --prompt 'a beautiful modelgraph' --num_inference_steps 50 --no_use_resolution_binning --enable_sequential_cpu_offload
flux_example.py:
`import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(filename)s[line:%(lineno)d]-%(levelname)s: %(message)s')
import time
import torch
import torch.distributed
import datetime
from transformers import T5EncoderModel
from xfuser import xFuserFluxPipeline, xFuserArgs
from xfuser.config import FlexibleArgumentParser
from xfuser.core.distributed import (
    get_world_group,
    get_data_parallel_rank,
    get_data_parallel_world_size,
    get_runtime_state,
    is_dp_last_group,
)


def main():
    parser = FlexibleArgumentParser(description="xFuser Arguments")
    args = xFuserArgs.add_cli_args(parser).parse_args()
    engine_args = xFuserArgs.from_cli_args(args)
    engine_config, input_config = engine_args.create_config()
    engine_config.runtime_config.dtype = torch.bfloat16
    local_rank = get_world_group().local_rank
    text_encoder_2 = T5EncoderModel.from_pretrained(engine_config.model_config.model, subfolder="text_encoder_2", torch_dtype=torch.bfloat16)


    pipe = xFuserFluxPipeline.from_pretrained(
        pretrained_model_name_or_path=engine_config.model_config.model,
        engine_config=engine_config,
        torch_dtype=torch.bfloat16,
        text_encoder_2=text_encoder_2,
        #device_map="balanced",
    )

    if args.enable_sequential_cpu_offload:
        pipe.enable_sequential_cpu_offload(gpu_id=local_rank)
        logging.info(f"rank {local_rank} sequential CPU offload enabled")
    else:
        pipe = pipe.to(f"cuda:{local_rank}")

    parameter_peak_memory = torch.cuda.max_memory_allocated(device=f"cuda:{local_rank}")

    pipe.prepare_run(input_config, steps=1)
    start_time = time.time()
    output = pipe(
        height=input_config.height,
        width=input_config.width,
        prompt=input_config.prompt,
        num_inference_steps=input_config.num_inference_steps,
        output_type=input_config.output_type,
        max_sequence_length=256,
        guidance_scale=1.0,
        generator=torch.Generator(device="cuda").manual_seed(input_config.seed),
    )
    end_time = time.time()
    elapsed_time = end_time - start_time
    peak_memory = torch.cuda.max_memory_allocated(device=f"cuda:{local_rank}")

    parallel_info = (
        f"dp{engine_args.data_parallel_degree}_cfg{engine_config.parallel_config.cfg_degree}_"
        f"ulysses{engine_args.ulysses_degree}_ring{engine_args.ring_degree}_"
        f"tp{engine_args.tensor_parallel_degree}_"
        f"pp{engine_args.pipefusion_parallel_degree}_patch{engine_args.num_pipeline_patch}"
    )
    if input_config.output_type == "pil":
        dp_group_index = get_data_parallel_rank()
        num_dp_groups = get_data_parallel_world_size()
        dp_batch_size = (input_config.batch_size + num_dp_groups - 1) // num_dp_groups
        if pipe.is_dp_last_group():
            for i, image in enumerate(output.images):
                image_rank = dp_group_index * dp_batch_size + i
                image_name = f"flux_result_{parallel_info}_{image_rank}_tc_{engine_args.use_torch_compile}.png"
                image.save(f"./results/{image_name}")
                logging.info(f"---------image {i} saved to ./results/{image_name}")

    if get_world_group().rank == get_world_group().world_size - 1:
        logging.info(f"epoch time: {elapsed_time:.2f} sec, parameter memory: {parameter_peak_memory/1e9:.2f} GB, memory: {peak_memory/1e9:.2f} GB")
    get_runtime_state().destory_distributed_env()


if __name__ == "__main__":
    main()

`

**Comment by feifeibear** [comment]
+ TASK_ARGS='--height 1024 --width 1024 --no_use_resolution_binning'
+ N_GPUS=2
+ PARALLEL_ARGS='--pipefusion_parallel_degree 2 --ulysses_degree 1 --ring_degree 1'
+ torchrun --nproc_per_node=2 ./examples/flux_example.py --model /cfs/dit/FLUX.1-dev --pipefusion_parallel_degree 2 --ulysses_degree 1 --ring_degree 1 --height 1024 --width 1024 --no_use_resolution_binning --num_inference_steps 28 --warmup_steps 1 --prompt 'brown dog laying on the ground with a metal bowl in front of him.'

I have checked by running with the above command. No error and success. I suggest you remove 
--enable_sequential_cpu_offload

and check did you install xdit correctly by pip install .

**Comment by feifeibear** [comment]
I have checked the main branch still works.
