### ISSUE TITLE
Some questions about PipeFusion

### ISSUE THREAD

**Issue by ictzyqq** [xdit-project/xDiT#360]
Hi, I have some questions about your project and your PipeFusion paper.
1. I don't understand how communication and computation can be overlapped when using PipeFusion with M=N. I think this overlap can only happen when M>N, because there will be a longer computation time between computing the same patch in two adjacent timesteps on each device. I also wonder whether this overlapping feature has been supported by xDiT?
2. Since PipeFusion does not work for Flux-shnell, which has only 4 timesteps, how can I use this model for inference on low VRAM devices besides quantizing the model? TP seems to be the only parallel algorithm to solve this problem. Do you have any plan to fully support TP in xDiT？
I'm looking forward to your reply. Thanks!

**Comment by feifeibear** [comment]
Hi, you can refer to our paper for these questions.

1. In pipefusion, the p2p has been overlapped with computation.

PipeFusion: Patch-level Pipeline Parallelism for Diffusion Transformers Inference
https://arxiv.org/abs/2405.14430

2. we have no plan to apply TP, please refer to paper for details. Pipefusion has already been implemented for flux-shnell, you can test it with example/run.sh

xDiT: an Inference Engine for Diffusion Transformers (DiTs) with Massive Parallelism
https://arxiv.org/abs/2411.01738

**Comment by ictzyqq** [comment]
> Hi, you can refer to our paper for these questions.
> 
> 1. In pipefusion, the p2p has been overlapped with computation.
> 
> PipeFusion: Patch-level Pipeline Parallelism for Diffusion Transformers Inference https://arxiv.org/abs/2405.14430
> 
> 2. we have no plan to apply TP, please refer to paper for details. Pipefusion has already been implemented for flux-shnell, you can test it with example/run.sh
> 
> xDiT: an Inference Engine for Diffusion Transformers (DiTs) with Massive Parallelism https://arxiv.org/abs/2411.01738

谢谢作者的回复！
1.关于第一点，论文中提到了"For example, at micro-step 4, device 0 receives P1’s activation from diffusion timestep T while concurrently computing the activation values for P0 at timestep T. Similarly, at the next micro-step, the transmission of P0 to device 1 can be hidden by the computation of P1 on the device."我能理解p2p与计算重叠的逻辑，但我认为在实际应用中做不到这种重叠：
![image](https://github.com/user-attachments/assets/aa33c539-d435-42ca-8a41-7caf48f43850)
device0在计算micro-step0的P0和计算micro-step4的P0之间，至少要等待P0在device1/2/3的计算以及4次P2P通信时间，无论怎么做通信计算重叠，都无法缩短这一段等待的时间，因此不存在device0接收P0的同时正在计算P3的情况（因为device0计算P3时P0还没从device3发出），实际的通信时间并不能被计算掩盖住，不知道我的理解是否正确？
2.关于第二点，我测了一下Flux-schnell，发现使能PipeFusion后生成的图片与使能之前区别不明显，这么看来即使模型的timesteps数很少，PipeFusion算法只对精度造成了很小的影响，确实完全优于TP。

**Comment by ictzyqq** [comment]
另外我观察到p2p通信的kernel貌似并没有与计算有任何的重叠，请问xDiT是还没有支持这个功能吗？
![image](https://github.com/user-attachments/assets/ec180ad4-4f54-4719-8122-ebb0aa7074d6)

**Comment by feifeibear** [comment]
1. 第一个问题。

你说”因此不存在device0接收P0的同时正在计算P3的情况“，这个我不太理解。如果device3的P0提前算法就可以开始了。你要知道，M可以数目不止4个，如果M>4，device 0很容易提前拿到P0.

2. 第二个问题。你发现xdit里面pipefusion的p2p没有重叠。这个我们可以确认一下。因为之前有人为了适配国产卡改了一下p2p部分的逻辑。理论上都是可以重叠的。

**Comment by ictzyqq** [comment]
> 1. 第一个问题。
> 
> 你说”因此不存在device0接收P0的同时正在计算P3的情况“，这个我不太理解。如果device3的P0提前算完就可以开始了。你要知道，M可以数目不止4个，如果M>4，device 0很容易提前拿到P0.
> 
> 2. 第二个问题。你发现xdit里面pipefusion的p2p没有重叠。这个我们可以确认一下。因为之前有人为了适配国产卡改了一下p2p部分的逻辑。理论上都是可以重叠的。另外，因为PipeFusion通信量很少，即使是同步的可能性能也不差，当然最好是异步的。
> 
> [f6fe00d](https://github.com/xdit-project/xDiT/commit/f6fe00d851b628ebcc3db0695c2f6fcb74e4f893)

感谢回复！
第一点我指的就是M=N的场景，假设每个patch在每个device的计算时间（也就是图中的每个矩形）都是一样的话，通信时间是无法被掩盖住的，device0计算完P3肯定比P0来的早。而论文的ablation study中说“M=N时最优，若M较小则会减少重叠效率”，因此我就对M=N时究竟有没有重叠收益感到了困惑。
目前我的理解是只有当每个device的计算时间不一样时（一般卡0和卡N-1会有额外计算）也许会有收益，计算时间最长的device可以消除其暴露出来的通信时间。
