### ISSUE TITLE
Time compute

### ISSUE THREAD

**Issue by thomasbtnfr** [xdit-project/xDiT#370]
Hello, after successfully running the xDiT example scripts for Flux or SD3, I'm wondering about the time computation.

In the example, we have this code:
```python
    start_time = time.time()
    output = pipe(
        height=input_config.height,
        width=input_config.width,
        prompt=input_config.prompt,
        num_inference_steps=input_config.num_inference_steps,
        output_type=input_config.output_type,
        max_sequence_length=256,
        guidance_scale=0.0,
        generator=torch.Generator(device="cuda").manual_seed(input_config.seed),
    )
    end_time = time.time()
    elapsed_time = end_time - start_time
 ```

We then display the elapsed_time value for the GPU with the highest RANK.

However, after displaying the value of `elapsed_time` for all GPUs, I can see that the values can be quite different... Sometimes there's a difference of several seconds.
So I'm wondering: is the current code correct? if so, why? is there a more robust method? should we take the maximum value of `elapsed_time` instead?

Thanks in advance!

**Comment by feifeibear** [comment]
You can use `cuda.synchronize()` before `end_time` or use `cuda_event`.

This is a common issue for timing multi-process programs. This cannot be considered as incorrect code.

**Comment by thomasbtnfr** [comment]
I've tried various options, including :
- `cuda.synchronize()` before end_time: doesn't change anything
- `cuda_event`: gives the same result as `time.time()`
In your benchmark results, which method do you use? The idea is to be consistent with your approach

**Comment by thomasbtnfr** [comment]
I see the idea, thanks!
