### ISSUE TITLE
max_sequence_length will lead to error

### ISSUE THREAD

**Issue by fy1214** [xdit-project/xDiT#380]
### Bug descripe:
**env:**
using 2 gpus
torch==2.5.1
xdit==0.3.5

**command:** 
python http-service/launch_host.py --config http-service/config.json

**config:**
`
          {
              "nproc_per_node": 2,
              "model": "/mnt/models/FLUX.1-schnell",
              "pipefusion_parallel_degree": 2,
              "ulysses_degree": 1,
              "ring_degree": 1,
              "height": 512,
              "width": 512,
              "save_disk_path": "./results/",
              "use_cfg_parallel": false,
              "max_queue_size": 4
          }
`
**it will lead to a runtime error:**
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/xDiT/./http-service/host.py", line 329, in <module>
[rank1]:     run_host()
[rank1]:   File "/home/xDiT/./http-service/host.py", line 310, in run_host
[rank1]:     generate_image_parallel(*params)
[rank1]:   File "/home/xDiT/./http-service/host.py", line 123, in generate_image_parallel
[rank1]:     output = pipe(
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 218, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 166, in data_parallel_fn
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/home/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 186, in check_naive_forward_fn
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/home/xDiT/xfuser/model_executor/pipelines/pipeline_flux.py", line 307, in __call__
[rank1]:     latents = self._sync_pipeline(
[rank1]:   File "/home/xDiT/xfuser/model_executor/pipelines/pipeline_flux.py", line 461, in _sync_pipeline
[rank1]:     latents, encoder_hidden_state = self._backbone_forward(
[rank1]:   File "/home/xDiT/xfuser/model_executor/pipelines/pipeline_flux.py", line 764, in _backbone_forward
[rank1]:     noise_pred, encoder_hidden_states = self.transformer(
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/xDiT/xfuser/model_executor/models/transformers/transformer_flux.py", line 207, in forward
[rank1]:     hidden_states = block(
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 92, in forward
[rank1]:     attn_output = self.attn(
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/xDiT/xfuser/model_executor/layers/attention_processor.py", line 158, in forward
[rank1]:     return self.processor(
[rank1]:   File "/home/xDiT/xfuser/model_executor/layers/attention_processor.py", line 668, in __call__
[rank1]:     query = apply_rotary_emb(query, image_rotary_emb)
[rank1]:   File "/opt/conda/envs/py10/lib/python3.10/site-packages/diffusers/models/embeddings.py", line 734, in apply_rotary_emb
[rank1]:     out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
[rank1]: RuntimeError: The size of tensor a (1280) must match the size of tensor b (1536) at non-singleton dimension 2

### **reason**
after i check the code， i found out that it's because host.py didn't set the max_sequence_length param

      def generate_image_parallel(
          prompt, num_inference_steps, seed, cfg, save_disk_path=None
      ):
          global pipe, local_rank, input_config
          logger.info(f"Starting image generation with prompt: {prompt}")
          torch.cuda.reset_peak_memory_stats()
          start_time = time.time()
          output = pipe(
              height=input_config.height,
              width=input_config.width,
              prompt=prompt,
              num_inference_steps=num_inference_steps,
              output_type="pil",
              generator=torch.Generator(device=f"cuda:{local_rank}").manual_seed(seed),
              guidance_scale=cfg,
          )

in pipe.prepare_run()， the max_sequence_length default is 256 because  the InputConfig's max_sequence_length default is 256:

      class InputConfig:
          height: int = 1024
          width: int = 1024
          num_frames: int = 49
          use_resolution_binning: bool = (True,)
          batch_size: Optional[int] = None
          prompt: Union[str, List[str]] = ""
          negative_prompt: Union[str, List[str]] = ""
          num_inference_steps: int = 20
          max_sequence_length: int = 256
          seed: int = 42
          output_type: str = "pil"

but in pipe.__call__， this param default is 512

      def __call__(
              self,
              prompt: Union[str, List[str]] = None,
              prompt_2: Optional[Union[str, List[str]]] = None,
              height: Optional[int] = None,
              width: Optional[int] = None,
              num_inference_steps: int = 28,
              timesteps: List[int] = None,
              guidance_scale: float = 7.0,
              num_images_per_prompt: Optional[int] = 1,
              generator: Optional[Union[torch.Generator, List[torch.Generator]]] = None,
              latents: Optional[torch.FloatTensor] = None,
              prompt_embeds: Optional[torch.FloatTensor] = None,
              pooled_prompt_embeds: Optional[torch.FloatTensor] = None,
              output_type: Optional[str] = "pil",
              return_dict: bool = True,
              joint_attention_kwargs: Optional[Dict[str, Any]] = None,
              callback_on_step_end: Optional[Callable[[int, int, Dict], None]] = None,
              callback_on_step_end_tensor_inputs: List[str] = ["latents"],
              max_sequence_length: int = 512,
              **kwargs,
          ):

this will cause the prompt_embeds size different, finally the encoder_hidden_state will change:
in prepare stage, the encoder_hidden_state's shape is [1, 256, 3072]
but in call stage, the encoder_hidden_state's shape is [1, 512, 3072]

but the problem is ,in prepare stage, the recv_buffer  recv_buffer["encoder_hidden_state"][0] is set to [1, 256, 3072] and it didn't reset in call stage.

so in call stage  rank1's encoder_hidden_state only received half of the tensor

        def _sync_pipeline(...)
            for i, t in enumerate(timesteps):
                .....
                else:
                    latents = get_pp_group().pipeline_recv()
                    if not is_pipeline_first_stage():
                    encoder_hidden_state = get_pp_group().pipeline_recv(
                        0, "encoder_hidden_state"
                    )

finally raise this exception.

### fix
after i set max_sequence_length to the pipe config, everything goes well

      def generate_image_parallel(
          prompt, num_inference_steps, seed, cfg, save_disk_path=None
      ):
          global pipe, local_rank, input_config
          logger.info(f"Starting image generation with prompt: {prompt}")
          torch.cuda.reset_peak_memory_stats()
          start_time = time.time()
          output = pipe(
              height=input_config.height,
              width=input_config.width,
              prompt=prompt,
              num_inference_steps=num_inference_steps,
              output_type="pil",
              generator=torch.Generator(device=f"cuda:{local_rank}").manual_seed(seed),
              guidance_scale=cfg,
              max_sequence_length=input_config.max_sequence_length
          )

**Comment by feifeibear** [comment]
Thanks for debugging! We would greatly appreciate it if you could submit a merge request to the xDiT repository. Your contribution will help us integrate your fixes and improvements seamlessly into our project.

**Comment by fy1214** [comment]
> Thanks for debugging! We would greatly appreciate it if you could submit a merge request to the xDiT repository. Your contribution will help us integrate your fixes and improvements seamlessly into our project.

sure
