### ISSUE TITLE
How to use xDiT speed cogvideox-5B-v1.5-I2V？

### ISSUE THREAD

**Issue by wen020** [xdit-project/xDiT#385]
How to use xDiT speed cogvideox-5B-v1.5-I2V？

**Comment by feifeibear** [comment]
https://github.com/xdit-project/xDiT/blob/main/examples/run_cogvideo.sh

Hi, you can refer to this script.

**Comment by Jake-wei** [comment]
> https://github.com/xdit-project/xDiT/blob/main/examples/run_cogvideo.sh
> 
> Hi, you can refer to this script.

It seems that cogvideoxpipeline in xidts doesn't support the inference of  cogvideox-5B-v1.5-I2V, because there is no input para of  image

**Comment by feifeibear** [comment]
> > https://github.com/xdit-project/xDiT/blob/main/examples/run_cogvideo.sh
> > Hi, you can refer to this script.
> 
> It seems that cogvideoxpipeline in xidts doesn't support the inference of cogvideox-5B-v1.5-I2V, because there is no input para of image

https://github.com/xdit-project/xDiT/issues/296

Currently, xDiT lacks an I2V (Image-to-Video) implementation example. However, you may refer to this issue thread for guidance on integrating the image encoder functionality. The implementation should be relatively straightforward. We would greatly appreciate it if you could contribute by submitting a PR to address this feature gap.
