### ISSUE TITLE
Add support for ConsisID

### ISSUE THREAD

**Issue by SHYuanBest** [xdit-project/xDiT#389]
@feifeibear Hi, we recently propose ConsisID, a tuning-free DiT-based controllable IPT2V model to keep human-identity consistent in the generated video, based on CogVideoX-5B. Can you help us to incorporating ConsisID into xDiT, thanks.

**Comment by feifeibear** [comment]
@SHYuanBest Thank you for your interest in our xDiT! You can refer to the following PRs to easily integrate the USP of xDiT into your model.


https://github.com/Tencent/HunyuanVideo/pull/68
https://github.com/xdit-project/mochi-xdit/commit/f90382be4f0d2b48ef5a05bcd24c33e900ddf76d
