### ISSUE TITLE
Do you have plan to support some Text to Speech Model？

### ISSUE THREAD

**Issue by ZhikangNiu** [xdit-project/xDiT#402]
Thanks for your meaningful work I found the examples are T2I and T2V work. Do you have a plan to support some Text to Speech Models, like https://github.com/SWivid/F5-TTS

**Comment by ZhikangNiu** [comment]
Its backbone is DiT

**Comment by ZhikangNiu** [comment]
Yeah, I will try. Thank you!

**Comment by ZhikangNiu** [comment]
> [@ZhikangNiu](https://github.com/ZhikangNiu) Have you tried this , we want to optimize the performance of [F5-TTS](https://github.com/SWivid/F5-TTS)

Nope, I don't have enough time to do this, If you are available, pls try this!

**Comment by DomoMKT** [comment]
"you can find what you're looking for, including high-quality text-to-speech conversions with extremely low latency, at [www.nemesyslabs.com](https://www.nemesyslabs.com)".
