### ISSUE TITLE
FLUX.1-dev run in MultiNodes error 

### ISSUE THREAD

**Issue by etersin** [xdit-project/xDiT#409]
env: machine A (4090  24G \*2） machine B(4090 24G \*2)

CMD  (machine A):
torchrun --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr=127.0.0.1 --master_port=6000 ./examples/flux_example.py --model=/cfs/dit/FLUX.1-dev/ --ulysses_degree=1 --ring_degree=1 --pipefusion_parallel_degree=4 --height=1024 --width=1024 --no_use_resolution_binning --output_type=latent --num_inference_steps 28 --warmup_steps=0 '--prompt=brown dog laying on the ground with a metal bowl in front of him.'
CMD (machine B):
torchrun --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr=ip_a --master_port=6000 ./examples/flux_example.py --model=/cfs/dit/FLUX.1-dev/ --ulysses_degree=1 --ring_degree=1 --pipefusion_parallel_degree=4 --height=1024 --width=1024 --no_use_resolution_binning --output_type=latent --num_inference_steps 28 --warmup_steps=0 '--prompt=brown dog laying on the ground with a metal bowl in front of him.'

Error:
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 4096 (input tensor's size at dimension -2), but got split_sizes=[4096, 4096, 4096, 4096]

Logging info:

![image](https://github.com/user-attachments/assets/20af14c8-abe1-42a8-8ff1-d134c217b0a8)
![image](https://github.com/user-attachments/assets/72cb38c6-24b6-4e77-af2e-cfe901b8c790)
![image](https://github.com/user-attachments/assets/5d5e9c41-eb36-4faf-a64e-411f1585a076)

**Comment by feifeibear** [comment]
Please ensure you are using Diffusers version 0.31.0. If you are currently using version 0.32.0, you may encounter errors. We are actively working to resolve these issues and will release a fix for version 0.32.0 as soon as possible.

Thank you for your patience and understanding.
