### ISSUE TITLE
Buffer 优化

### ISSUE THREAD

**Issue by Steaunk** [xdit-project/xDiT#82]
https://github.com/PipeFusion/PipeFusion/blob/main/pipefuser/utils.py#L196C9-L196C27

在之前的实现中，出于简便的目的，分别对 warmup 阶段和 pipefusion 阶段的通信建立了两个同样大小但是不同类型的 buffer。
1. warmup 阶段创建了一整段buffer；
2. pipefusion 阶段根据 pp_num_batch，创建了多段小 buffer。

由于warmup阶段和pipefusion阶段不会同时出现，实际上可以将其合并为一段 buffer 来减小内存占用。

**Comment by feifeibear** [comment]
We have updated the API. The issue is related to the legacy API.
